version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: iris
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  preprocess:
    build:
      context: ./preprocess
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: iris
      DB_USER: user
      DB_PASS: password

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    depends_on:
      - preprocess
    environment:
      DB_HOST: db
      DB_NAME: iris
      DB_USER: user
      DB_PASS: password

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - model
    environment:
      DB_HOST: db
      DB_NAME: iris
      DB_USER: user
      DB_PASS: password

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.2.1
    ports:
      - "5000:5000"
    environment:
      - MLFLOW_TRACKING_URI=http://0.0.0.0:5000
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow ui --host 0.0.0.0

volumes:
  pgdata:
