version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Joe13102004
      POSTGRES_DB: iris
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.2.1
    container_name: mlflow
    ports:
      - "5000:5000"
    command: mlflow ui --host 0.0.0.0

  api:
    build: ./api
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mlflow
    environment:
      DB_HOST: db
      DB_NAME: iris
      DB_USER: postgres
      DB_PASS: Joe13102004
      MLFLOW_TRACKING_URI: http://mlflow:5000

  preprocess:
    build: ./preprocess
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: iris
      DB_USER: postgres
      DB_PASS: Joe13102004

  trainer:
    build: ./model
    depends_on:
      - db
      - preprocess
    environment:
      DB_HOST: db
      DB_NAME: iris
      DB_USER: postgres
      DB_PASS: Joe13102004
      MLFLOW_TRACKING_URI: http://mlflow:5000

volumes:
  pgdata:
